DRIV-6546 and DRIV-6545
control4/drivers-driverpackager pull request #10
Opened 2021-09-21 12:18 UTC by MJovanovicC4

Features:

- Updating `modified` date
- Passing an argument with the driver version to update the `version` tag into

2021-09-21 12:23 UTC, WWalshC4 approved these changes
I like these improvements, and I really like the use of named flagged arguments vs positional args.

2021-09-27 13:01 UTC, FDrazicC4 requested changes
Let's also update the GitHub action and its documentation.

2021-09-27 13:01 UTC, FDrazicC4 commented on dp3/driverpackager.py
> +    parser.add_argument("-um", "--updatemodified", action="store_true",
I think that we should use --update-modified.

2021-09-27 13:01 UTC, FDrazicC4 commented on dp3/driverpackager.py
> +    parser.add_argument("-uv", "--updateversion", nargs=1,
I think that we should use --update-version.

2021-10-04 08:51 UTC, FDrazicC4 approved these changes

2021-10-04 08:51 UTC, merged